# Generated by Django 4.0 on 2023-02-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_wallet_accountname_wallet_accountnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='accountName',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='accountNumber',
            new_name='account_number',
        ),
    ]
